server:
    port: 8082
    context-path: /app2
security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      accessTokenUri: http://localhost:8080/authserver/oauth/token
      userAuthorizationUri: http://localhost:8080/authserver/oauth/authorize
    resource:
      userInfoUri: http://localhost:8080/authserver/user
